name 'jtopjian-apt-mirror'
version '1.0.0'
source 'git://github.com/jtopjian/puppet-apt-mirror.git'
author 'jtopjian'
license 'Apache 2.0'
summary 'A simple module to work with apt-mirror'
description 'This module manages apt-mirror. You can add mirrors on a per-mirror basis.'
project_page 'https://github.com/jtopjian/puppet-apt-mirror'
dependency 'puppetlabs/concat', '>= 0.2.0'
